### ISSUE TITLE
Installing qgis-better-editor crashes QGis

### ISSUE THREAD

**Issue by dd-a** [YoannQDQ/qgis-better-editor#1]
Hi !
I'm using QGis 3.12 (official build) on Mac OS 10.15.5 , and when I installed qgis-better-editor (v 1.1) QGis crashed immediately.  I got the following error message after restarting QGis with all the other plugins removed, and re-activating bettereditor:

`Impossible de charger l'extension 'bettereditor' provoque une erreur lors de l'appel à sa méthode initGui() 

AttributeError: module 'subprocess' has no attribute 'CREATE_NO_WINDOW' 
Traceback (most recent call last):
  File "/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/bettereditor/dependencies.py", line 31, in import_or_install
    return importlib.import_module(dep)
  File "/Applications/QGIS3.12.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "", line 1006, in _gcd_import
  File "", line 983, in _find_and_load
  File "", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'black'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/QGIS3.12.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 359, in startPlugin
    plugins[packageName].initGui()
  File "/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/bettereditor/bettereditor.py", line 179, in initGui
    self.check_dependencies()
  File "/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/bettereditor/bettereditor.py", line 252, in check_dependencies
    self.black = import_or_install("black")
  File "/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/bettereditor/dependencies.py", line 33, in import_or_install
    return resolve(dep)[0]
  File "/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/bettereditor/dependencies.py", line 16, in resolve
    output = subprocess.check_output(cmd, creationflags=subprocess.CREATE_NO_WINDOW)
AttributeError: module 'subprocess' has no attribute 'CREATE_NO_WINDOW'

Version de Python : 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)] 
Version de QGIS : 3.12.3-București București, 8234261527 

Chemin Python :
/Applications/QGIS3.12.app/Contents/MacOS/../Resources/python
/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.12.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS3.12.app/Contents/Resources/python
/Applications/QGIS3.12.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages
/Applications/QGIS3.12.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python37.zip
/Applications/QGIS3.12.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7
/Applications/QGIS3.12.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/lib-dynload
/Applications/QGIS3.12.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages/geos
/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python`

My QGis install:

Version de QGIS | 3.12.3-București | Révision du code | 8234261527
-- | -- | -- | --
Compilé avec Qt | 5.12.3 | Utilisant Qt | 5.12.3
Compilé avec GDAL/OGR | 2.4.1 | Utilisé avec GDAL/OGR | 2.4.1
Compilé avec GEOS | 3.7.2-CAPI-1.11.2 | Utilisé avec GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compilé avec SQLite | 3.28.0 | Fonctionne avec SQLite | 3.28.0
Version du client PostgreSQL | 11.3 | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.1
Compilé avec PROJ | 5.2.0 | Fonctionne avec PROJ | Rel. 5.2.0, September 15th, 2018
Version de l'OS | macOS 10.15

**Comment by YoannQDQ** [comment]
Strange... Python version is 3.7 so  'CREATE_NO_WINDOW' should be defined.
I assume it's related to your env config, but I'm not familiar with Mac OS...

With the plugin uninstalled, could you try to type in the embedded console?
```
import sys
print(sys.version)
import subprocess
print(subprocess.CREATE_NO_WINDOW)
```

**Comment by dd-a** [comment]
Ok, here's the result:

`import sys`
`print(sys.version)`
`3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]`
`import subprocess`
`print(subprocess.CREATE_NO_WINDOW)`
`Traceback (most recent call last):
  File "/Applications/QGIS3.12.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
AttributeError: module 'subprocess' has no attribute 'CREATE_NO_WINDOW'`

**Comment by YoannQDQ** [comment]
Ok, I uploaded a 1.1.1 version of the plugin. Once it is approved, give it a try and let me know if your problem is fixed.

**Comment by dd-a** [comment]
Ok, I'll check. 
Thanks !

**Comment by YoannQDQ** [comment]
Yeah, after double checking, [CREATE_NO_WINDOW](https://docs.python.org/3/library/subprocess.html#windows-constants) is documented as a Windows-only constant. No wonder it didn't work then. Closing the issue, thanks for your feedback!
