### ISSUE TITLE
Need to update for Qgis 3.16

### ISSUE THREAD

**Issue by nicogodet** [YoannQDQ/qgis-better-editor#4]
In current Qgis-Master (future 3.16), a lot of changes has been made in python editor and python console.
Unfortunately, I can't list all the bug in BetterEditor introduced by those changes

Here is 2 python errors : 
When I unload the extension
> 2020-10-22T11:08:51     WARNING    TypeError: event(self, QEvent): first argument of unbound method must have type 'QgsCodeEditorPython'

When I try to edit a script             

> 2020-10-22T11:13:12     WARNING    Traceback (most recent call last):
>               File "D:/Qgis/apps/qgis-dev/./python/plugins\processing\script\EditScriptAction.py", line 50, in execute
>               dlg.show()
>               File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\bettereditor\customclasses.py", line 633, in show
>               self.customize()
>               File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\bettereditor\customclasses.py", line 639, in customize
>               self.editor.customize()
>               File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\bettereditor\customclasses.py", line 609, in customize
>               define_indicators(self)
>               File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\bettereditor\indicatorsutils.py", line 61, in define_indicators
>               Editor.MARKER_NUM,
>              AttributeError: type object 'Editor' has no attribute 'MARKER_NUM'

**Comment by vovchykbratyk** [comment]
ran into this today as well, Ubuntu 21.04

**Comment by kannes** [comment]
For me 3.22.4 on Ubuntu 22.04 it also crashes with `Fatal: Assertion [cpMax <= pdoc->Length()] failed at ../src/Editor.cpp 6096` if I try to enter anything (used a space for testing) in a Python script editor.
